- .gitignore
- .travis.yml
- fedmsg_meta_umb/tests/test_brew_import.py
- fedmsg_meta_umb/tests/test_brew_task.py
- setup.cfg
- setup.py
Configure Travis CI to run flake8. Reformat some code to make flake8 happy.
> Run flake8 during Travis CI builds

- .gitignore
- README.rst
- fedmsg_meta_umb/tests/test_brew_build.py
- fedmsg_meta_umb/tests/test_brew_import.py
- fedmsg_meta_umb/tests/test_brew_package.py
- fedmsg_meta_umb/tests/test_brew_repo.py
- fedmsg_meta_umb/tests/test_brew_sign.py
- fedmsg_meta_umb/tests/test_brew_task.py
- tox.ini
`detox` is just `tox` that runs in parallel.
> Use tox to run tests on py27 and py35.

- fedmsg_meta_umb/rpmdiff.py
- fedmsg_meta_umb/tests/test_rpmdiff.py
- setup.py
Processor and tests for rpmdiff messages.
> Handle RPMDiff messages.

- fedmsg_meta_umb/distgit.py
- fedmsg_meta_umb/tests/test_distgit.py
- setup.py
Processor and tests for messages from distgit.
> handle distgit messages

- fedmsg_meta_umb/errata.py
- fedmsg_meta_umb/tests/test_errata.py
- setup.py
This handles only a few of the many errata tool message types... but it's a start!
> Preliminary errata tool support.

- fedmsg_meta_umb/pub.py
> Careful with "pushed_by".

- fedmsg_meta_umb/robosignatory.py
- fedmsg_meta_umb/tests/test_robosignatory.py
- setup.py
Just the basics.
I'd love to have a url here too.. but not sure where to point it.  Perhaps at a registry associated with pub?
> Processor for robosignatory events.

- fedmsg_meta_umb/tests/test_tps.py
- fedmsg_meta_umb/tps.py
- setup.py
Initial revision for support for TPS. This is still WIP.
> Support for TPS

- fedmsg_meta_umb/freshmaker.py
- fedmsg_meta_umb/tests/test_freshmaker.py
- setup.py
Signed-off-by: Chenxiong Qi <cqi@redhat.com>
> Processor for freshmaker events

- fedmsg_meta_umb/freshmaker.py
- fedmsg_meta_umb/tests/test_freshmaker.py
> Freshmaker logo.

- fedmsg_meta_umb/resultsdb.py
- fedmsg_meta_umb/tests/test_resultsdb.py
- setup.py
I tried to add tests both for the happy and unhappy paths.
> A processor for resultsdb messages.

- fedmsg_meta_umb/errata.py
- fedmsg_meta_umb/tests/test_errata.py
> support errata.activity.text_changes messages

- fedmsg_meta_umb/cips.py
- fedmsg_meta_umb/tests/test_cips.py
Signed-off-by: shanks <grajaiya@redhat.com>
> Include VirtualTopic.eng.cips.running topic to CIPS

- fedmsg_meta_umb/pungi.py
- fedmsg_meta_umb/tests/test_pungi.py
This is marked as a new compose status.
Related: https://pagure.io/pungi/pull-request/946
> Handle Pungi compose being terminated

- fedmsg_meta_umb/ci.py
- fedmsg_meta_umb/tests/test_ci.py
- setup.py
To add support for processing `/topic/VirtualTopic.eng.ci.>` messages.
> Add support for CI messages

- fedmsg_meta_umb/jira.py
- fedmsg_meta_umb/tests/test_jira.py
- setup.py
These are produced by small microservice webhook triggered by JIRA
server. See https://docs.engineering.redhat.com/x/pa7FAw
> Add processor for JIRA messages

- fedmsg_meta_umb/brew.py
- fedmsg_meta_umb/distgit.py
- fedmsg_meta_umb/errata.py
- fedmsg_meta_umb/freshmaker.py
- fedmsg_meta_umb/greenwave.py
- fedmsg_meta_umb/mbs.py
- fedmsg_meta_umb/tests/test_brew_build.py
- fedmsg_meta_umb/tests/test_distgit.py
- fedmsg_meta_umb/tests/test_errata.py
- fedmsg_meta_umb/tests/test_freshmaker.py
- fedmsg_meta_umb/tests/test_greenwave.py
- fedmsg_meta_umb/tests/test_mbs.py
... I put them everywhere I could think of.
> Put estuary links everywhere.

- fedmsg_meta_umb/freshmaker.py
- fedmsg_meta_umb/tests/test_freshmaker.py
This message was recently added to Freshmaker:
https://pagure.io/freshmaker/c/c57bf2eea2ea054d11ea16c371810f54508686dd
Signed-off-by: Luiz Carvalho <lucarval@redhat.com>
> Add support for event.state.changed.min msg

- .travis.yml
- tox.ini
Also run flake8 and docs tests under python 3.7.
> update tests to python 3.7

- fedmsg_meta_umb/aqe_jenkins.py
- fedmsg_meta_umb/tests/test_aqe_jenkins.py
- setup.py
@mikebonnet I try to replicate what's done in all the other services, but unit tests won't pass and I can't figure out why. Would you be able to take a look and see what I'm missing please?
> Add message processor for Retrobob

- fedmsg_meta_umb/brew.py
- fedmsg_meta_umb/tests/test_brew_kojira.py
I've written new 'plugin' for sending messages about expired repositories from kojira. It introduces new message type, so here is a PR with subtitle/link templates.
> handle subtitle/link for brew.kojira.expired messages

- .travis.yml
- python-fedmsg-meta-umb.spec
- setup.py
- tox.ini
since fedmsg no longer supports it as of Fedora 31
> remove python2 support
