- fedmsg_meta_umb/brew.py
- fedmsg_meta_umb/tests/test_brew_build.py
Builds that have been imported send messages with fewer fields defined.
Specifically, info['nvr'] and info['owner_name'] are missing. Update
the code to handle these messages gracefully.
> handle imported builds

- .travis.yml
- README.rst
- tox.ini
Run tests on python 3.5 in Travis CI. Use tox when running tests in Travis CI, for consistency with local testing. Get code coverage reports from codecov.io.
> more CI improvements

- datagrepper-docs/charts.rst
- datagrepper-docs/index.rst
- datagrepper-docs/reference.rst
- datagrepper-docs/widget.rst
These can be referenced by fedora-infra/datagrepper#193.
... I just don't know where else to put them for now.  Eventually, they
should go in an ansible repo or better a repo containing the Dockerfile
we use to define our container for openshift deployment.
For now, can they live here?
> Add some datagrepper docs.

- fedmsg_meta_umb/pungi.py
- fedmsg_meta_umb/tests/test_pungi.py
- setup.py
There's one odd extra example in the test suite for producing ostrees.
I know pungi can do this, but it doesn't seem to be enabled or turned on
in prod -- I didn't find any example messages in our dev datagrepper
instance.
> Handle pungi messages.

- setup.py
It is used in `tox.ini`... but that pulls it into the virtualenv at test
time.  Am I missing something?
> I don't think flake8 is actually required for setup.

- fedmsg_meta_umb/pub.py
- fedmsg_meta_umb/tests/test_pub.py
pub.container.sign messages have a different format than other pub messages, so the pub translator was causing errors. Special-case these messages.
> pub.container.sign messages are special

- fedmsg_meta_umb/rhchi.py
- fedmsg_meta_umb/tests/test_rhchi.py
Handle "started" messages which don't include a "status" header. Also, added some tests for rhchi.functional messages.
> Fix the rhchi processor for "started" messages.

- fedmsg_meta_umb/errata.py
- fedmsg_meta_umb/tests/test_errata.py
CCAT reschedule messages look a little different than other Errata Tool
messages. They don't have a who field in the headers, and the header
and body keys are in upper-case. This updates the errata handler to
account for those differences.
> errata.py: handle CCAT reschedule messages

- fedmsg_meta_umb/errata.py
- fedmsg_meta_umb/tests/test_errata.py
These message types were added in addition to the errata.builds.changed message.
One is sent for each build that is added or removed from an errata.
> support errata.builds.added and errata.builds.removed messages

- fedmsg_meta_umb/odcs.py
Should look nice to show `freshmaker` instead of `freshmaker/freshmaker.engineering.blahblah.com`.
> Strip the host information out of service principal for display.

- fedmsg_meta_umb/metaxor.py
- fedmsg_meta_umb/tests/test_metaxor.py
- setup.py
At the moment MetaXOR produces 3 types of messages:
* New containerImage getting inserted
* containerImage getting updated
* When MetaXOR finished refreshing whole repository
More message types will be coming in the future.
> Add initial MetaXOR metadata processors

- fedmsg_meta_umb/metaxor.py
- fedmsg_meta_umb/tests/test_metaxor.py
Previous code assumed all message bodies are dict objects. MetaXOR has
internal topic used for command and control activities. Not all of these
messages are dictionaries.
> [MetaXOR] Fix handling of non-dict messages

- fedmsg_meta_umb/metaxor.py
- fedmsg_meta_umb/tests/test_metaxor.py
MX started producing messages when new or existing repository is created
or updated in database.
The messages are sent to following topics:
- metaxor.events.lightblue.containerRepository.insert
- metaxor.events.lightblue.containerRepository.update
> Add handlers for Metaxor's container repo messages

- fedmsg_meta_umb/greenwave.py
- fedmsg_meta_umb/tests/test_greenwave.py
The decision updates for compose gate have different item type.
Make sure to support it in packages mapping.
Signed-off-by: Miroslav Vadkerti <mvadkert@redhat.com>
> greenwave: add support for brew-build type

- fedmsg_meta_umb/resultsdb.py
- fedmsg_meta_umb/tests/test_resultsdb.py
We started publishing this message change months ago, but are just now getting
around to updating fedmsg_meta.
The old tests were converted to "Legacy" tests, so we can be sure they'll still
render in datagrepper, but won't be published to the documentation.
> ResultsDB: Handle new format.

- fedmsg_meta_umb/odcs.py
datanommer expects the usernames() method to always return a set (not None).
Also, return a message from subtitle() even for unknown messages.
> odcs: always return a set from usernames()

- MANIFEST.in
- fedmsg_meta_umb/doc_utilities.py
- python-fedmsg-meta-umb.spec
- setup.py
The subpackage contains the customized theme for the datagrepper
web UI, and documentation on the topics and message formats used
on the Unified Message Bus.
> build a -docs subpackage

- python-fedmsg-meta-umb.spec
Rename subpackage to -doc in accordance with Fedora recommendations.
Don't install docs as %%doc files, because dnf in a container runs with tsflags=nodocs.
> specfile fixes

- fedmsg_meta_umb/errata.py
- fedmsg_meta_umb/tests/test_errata.py
This adds subtitle support for UMB messages on the errata.ccat topic.
The format for the message came from the request at
https://projects.engineering.redhat.com/browse/FACTORY-2250
> Add subtitle handler for cat messages

- fedmsg_meta_umb/jira.py
- fedmsg_meta_umb/tests/test_jira.py
This makes two changes - adds usernames and also tweaks for new topics (comment added/removed). 
Comment addition now actually triggers two identical messages in different topics. This is because single update can make other changes besides the comment change
> Add usernames

- fedmsg_meta_umb/metaxor.py
- fedmsg_meta_umb/tests/test_metaxor.py
Metaxor uses UMB as communication channel between handlers and workers.
This commit adds handler for internal MX communication. In this specific
case it handles repository refresh requests. In future there will be
more internal handlers like this.
> Metaxor: Add new handler for internal requests

- fedmsg_meta_umb/doc_utilities.py
- fedmsg_meta_umb/freshmaker.py
- fedmsg_meta_umb/greenwave.py
- fedmsg_meta_umb/mbs.py
- fedmsg_meta_umb/metaxor.py
- fedmsg_meta_umb/odcs.py
- fedmsg_meta_umb/resultsdb.py
- fedmsg_meta_umb/tests/test_freshmaker.py
- fedmsg_meta_umb/tests/test_greenwave.py
- fedmsg_meta_umb/tests/test_mbs.py
- fedmsg_meta_umb/tests/test_metaxor.py
- fedmsg_meta_umb/tests/test_odcs.py
- fedmsg_meta_umb/tests/test_resultsdb.py
Use links relative to the current hostname, rather than absolute URLs.
> replace links to the old datagrepper instance

- fedmsg_meta_umb/doc_utilities.py
Reported by Greg Allen.  Most of the links from our docs here time out when
they get to datagrepper.  Providing some limiting arguments like this will make
it possible for datagrepper to respond in time.
> Add a limiting suffix to datagrepper example links.

- .copr/Makefile
> install python3-setuptools in the copr chroot

- fedmsg_meta_umb/robosignatory.py
- fedmsg_meta_umb/tests/test_robosignatory.py
Often times when debugging, a pub task id was given. Adding that to
the subtitle makes tracking down the related messages easier. Also
remove robosignatory from subtitle since it's already in the topic
> Add pub task id to robosignatory subtitle

- fedmsg_meta_umb/tests/test_ci.py
- fedmsg_meta_umb/tests/test_cips.py
- fedmsg_meta_umb/tests/test_freshmaker.py
- fedmsg_meta_umb/tests/test_jira.py
- fedmsg_meta_umb/tests/test_odcs.py
- fedmsg_meta_umb/tests/test_tower.py
This will ensure all test suites are included in the auto-generated documentation.
Also remove a rogue back-quote from test_ci.py.
> add missing add_doc() calls to test suites

- fedmsg_meta_umb/snitch.py
- fedmsg_meta_umb/tests/test_snitch.py
Snitch produces messages based on MongoDB data. We found out that _id
fields in database are inconsistent and contains mix of strings and
ObjectId.
This commit handles both types of Snitch messages.
> Handle inconsistent IDs in Snitch messages

- .travis.yml
- fedmsg_meta_umb/rpmdiff.py
- fedmsg_meta_umb/tests/test_rpmdiff.py
- tox.ini
The Errata Tool icon is no longer available at the URL being used by
the rpmdiff processor. Replace it with a reference to a local copy.
Also update the docs link to point to the EXD Catalog. The Mojo
page is no longer available.
> rpmdiff: reference local Errata Tool icon

- fedmsg_meta_umb/pub.py
- fedmsg_meta_umb/tests/test_pub.py
The Errata Tool icon is no longer available at the URL being used by
the pub processor. Replace it with a reference to a local copy.
> pub: reference local Errata Tool icon

- fedmsg_meta_umb/clair.py
- fedmsg_meta_umb/tests/test_clair.py
In Clair v4 a message format changed a bit. NVRA is no longer available
and it was replaced by image_id.
This commit also unifies strings in Clair related files. All strings
uses double quotes now.
> Clair: handle messages from Clair v4

- .copr/Makefile
The user running the git command is different than the user that owns the git checkout
because the Makefile is run inside a mock environment, with the git checkout bind-mounted
into it. `git log` is used to include the commit hash in the srpm `Release` value, but Git
refuses to read any files owned by a different user unless safe.checkout is set.
> set safe.directory so git will read files owned by a different user

- .gitignore
- doc/requirements.txt
- fedmsg_meta_umb/doc_utilities.py
- python-fedmsg-meta-umb.spec
- setup.py
- tox.ini
`nose` is not supported under Python 3.12, switch to running tests with `unittest`.
Use the `develop` branch of `fedmsg` directly, since Python 3.12 support was recently added there but has not made it into a release.
Report test coverage.
> Support Python 3.12
